COUNTY_CHOICES = (
    ('Asbury Park', 'Asbury Park'),
    ('Atlantic City', 'Atlantic City'),
    ('Belleville', 'Belleville'),
    ('Berkeley', 'Berkeley'),
    ('Brick', 'Brick'),
    ('Bridgeton', 'Bridgeton'),
    ('Cherry Hill', 'Cherry Hill'),
    ('Collingswood', 'Collingswood'),
    ('Delran', 'Delran'),
    ('East Brunswick', 'East Brunswick'),
    ('Edison', 'Edison'),
    ('Egg Harbor', 'Egg Harbor'),
    ('Elizabeth', 'Elizabeth'),
    ('Englewood', 'Englewood'),
    ('Franklin (Gloucester)', 'Franklin (Gloucester)'),
    ('Franklin (Somerset)', 'Franklin (Somerset)'),
    ('Galloway', 'Galloway'),
    ('Gloucester', 'Gloucester'),
    ('Haddon', 'Haddon'),
    ('Hamilton', 'Hamilton'),
    ('Hammonton', 'Hammonton'),
    ('Highland Park', 'Highland Park'),
    ('Hopatcong', 'Hopatcong'),
    ('Howell', 'Howell'),
    ('Jersey City', 'Jersey City'),
    ('Lakewood', 'Lakewood'),
    ('Linden', 'Linden'),
    ('Lindenwold', 'Lindenwold'),
    ('Little Egg Harbor', 'Little Egg Harbor'),
    ('Livingston', 'Livingston'),
    ('Marlboro', 'Marlboro'),
    ('Medford', 'Medford'),
    ('Middletown', 'Middletown'),
    ('Millville', 'Millville'),
    ('Monroe', 'Monroe'),
    ('Mt. Laurel', 'Mt. Laurel'),
    ('Neptune', 'Neptune'),
    ('New Brunswick', 'New Brunswick'),
    ('North Brunswick', 'North Brunswick'),
    ('Ocean', 'Ocean'),
    ('Old Bridge', 'Old Bridge'),
    ('Passaic', 'Passaic'),
    ('Paterson', 'Paterson'),
    ('Pemberton', 'Pemberton'),
    ('Pennsville', 'Pennsville'),
    ('Perth Amboy', 'Perth Amboy'),
    ('Piscataway', 'Piscataway'),
    ('Plainfield', 'Plainfield'),
    ('Pleasantville', 'Pleasantville'),
    ('South Plainfield', 'South Plainfield'),
    ('Toms River', 'Toms River'),
    ('Trenton', 'Trenton'),
    ('Union', 'Union'),
    ('Vineland', 'Vineland'),
    ('Washington', 'Washington'),
    ('West New York', 'West New York'),
    ('Willingboro', 'Willingboro'),
    ('Winslow', 'Winslow'),
    ('Woodbridge', 'Woodbridge'),
    ('Woodbury', 'Woodbury'),
)

STATUS_CHOICES = (
    ('bankruptcy', 'bankruptcy'),
    ('backruptcy/redeemed', 'backruptcy/redeemed'),
    ('foreclosure', 'foreclosure'),
    ('foreclosure/redeemed', 'foreclosure/redeemed'),
    ('no-subs', 'no-subs'),
    ('own', 'own'),
    ('redeemed', 'redeemed'),
)

SUB_TYPE_CHOICES = (
    ('tax', 'tax'),
    ('utility', 'utility'),
    ('other', 'other'),
)