# Generated by Django 2.2.5 on 2019-11-30 04:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_id', models.IntegerField(unique=True)),
                ('county', models.CharField(choices=[('Asbury Park', 'Asbury Park'), ('Atlantic City', 'Atlantic City'), ('Belleville', 'Belleville'), ('Berkeley', 'Berkeley'), ('Brick', 'Brick'), ('Bridgeton', 'Bridgeton'), ('Cherry Hill', 'Cherry Hill'), ('Collingswood', 'Collingswood'), ('Delran', 'Delran'), ('East Brunswick', 'East Brunswick'), ('Edison', 'Edison'), ('Egg Harbor', 'Egg Harbor'), ('Elizabeth', 'Elizabeth'), ('Englewood', 'Englewood'), ('Franklin (Gloucester)', 'Franklin (Gloucester)'), ('Franklin (Somerset)', 'Franklin (Somerset)'), ('Galloway', 'Galloway'), ('Gloucester', 'Gloucester'), ('Haddon', 'Haddon'), ('Hamilton', 'Hamilton'), ('Hammonton', 'Hammonton'), ('Highland Park', 'Highland Park'), ('Hopatcong', 'Hopatcong'), ('Howell', 'Howell'), ('Jersey City', 'Jersey City'), ('Lakewood', 'Lakewood'), ('Linden', 'Linden'), ('Lindenwold', 'Lindenwold'), ('Little Egg Harbor', 'Little Egg Harbor'), ('Livingston', 'Livingston'), ('Marlboro', 'Marlboro'), ('Medford', 'Medford'), ('Middletown', 'Middletown'), ('Millville', 'Millville'), ('Monroe', 'Monroe'), ('Mt. Laurel', 'Mt. Laurel'), ('Neptune', 'Neptune'), ('New Brunswick', 'New Brunswick'), ('North Brunswick', 'North Brunswick'), ('Ocean', 'Ocean'), ('Old Bridge', 'Old Bridge'), ('Passaic', 'Passaic'), ('Paterson', 'Paterson'), ('Pemberton', 'Pemberton'), ('Pennsville', 'Pennsville'), ('Perth Amboy', 'Perth Amboy'), ('Piscataway', 'Piscataway'), ('Plainfield', 'Plainfield'), ('Pleasantville', 'Pleasantville'), ('South Plainfield', 'South Plainfield'), ('Toms River', 'Toms River'), ('Trenton', 'Trenton'), ('Union', 'Union'), ('Vineland', 'Vineland'), ('Washington', 'Washington'), ('West New York', 'West New York'), ('Willingboro', 'Willingboro'), ('Winslow', 'Winslow'), ('Woodbridge', 'Woodbridge'), ('Woodbury', 'Woodbury')], max_length=255)),
                ('year', models.IntegerField()),
                ('llc', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
                ('qualifier', models.CharField(blank=True, default='', max_length=255)),
                ('advertisement_number', models.IntegerField(blank=True, null=True)),
                ('mua_number', models.CharField(blank=True, default='', max_length=255)),
                ('certificate_number', models.CharField(default='', max_length=255)),
                ('lien_type', models.CharField(blank=True, default='', max_length=255)),
                ('list_item', models.CharField(blank=True, default='', max_length=255)),
                ('current_owner', models.CharField(blank=True, default='', max_length=255)),
                ('longitude', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=19)),
                ('assessed_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('status', models.CharField(blank=True, choices=[('bankruptcy', 'bankruptcy'), ('backruptcy/redeemed', 'backruptcy/redeemed'), ('foreclosure', 'foreclosure'), ('foreclosure/redeemed', 'foreclosure/redeemed'), ('no-subs', 'no-subs'), ('own', 'own'), ('redeemed', 'redeemed')], default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('certificate_face_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('winning_bid_percentage', models.DecimalField(decimal_places=4, max_digits=13)),
                ('premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('recording_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('recording_date', models.DateField(blank=True, null=True)),
                ('search_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('year_end_penalty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('flat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('cert_int', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('total_subs_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('total_cash_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('total_principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('total_actual_interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('total_legal_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('total_principal_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('notes', models.TextField(blank=True, default='', max_length=255)),
                ('redemption_date', models.DateField(blank=True, null=True)),
                ('redemption_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=11)),
            ],
            options={
                'ordering': ['county', 'lien_id'],
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('tax', 'tax'), ('utility', 'utility'), ('other', 'other')], max_length=255)),
                ('sub_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_jersey.Lien')),
            ],
            options={
                'order_with_respect_to': 'lien',
            },
        ),
    ]
